produce_list = [
    "APPLE", "BANANA", "ORANGE", "PINEAPPLE", "STRAWBERRY",
    "WATERMELON", "AVOCADO", "CUCUMBER", "TOMATO", "POTATO",
    "BROCCOLI", "CAULIFLOWER", "EGGPLANT", "SPINACH", "CARROT",
    "MUSHROOM", "ASPARAGUS", "ZUCCHINI", "BLUEBERRY", "RASPBERRY",
    "PEACH", "PLUM", "PEAR", "GRAPE", "CHERRY",
    "LEMON", "LIME", "KIWI", "MANGO", "PAPAYA",
    "APRICOT", "CANTALOUPE", "HONEYDEW", "FIG", "NECTARINE",
    "CRANBERRY", "COCONUT", "OLIVE", "GRAPEFRUIT", "MANDARIN",
    "TANGERINE", "POMEGRANATE", "PASSIONFRUIT", "LYCHEE", "JACKFRUIT",
    "GUAVA", "DRAGONFRUIT", "STARFRUIT", "KUMQUAT", "QUINCE"
]

random_list = [
    # Professions
    "DOCTOR", "ENGINEER", "TEACHER", "LAWYER", "NURSE",
    "ACCOUNTANT", "PLUMBER", "CHEF", "ARTIST", "POLICE OFFICER",
    "FIREFIGHTER", "ARCHITECT", "SCIENTIST", "WRITER", "MECHANIC",
    
    # Locations
    "NEW YORK", "LONDON", "PARIS", "TOKYO", "MOSCOW",
    "SYDNEY", "ROME", "BERLIN", "DUBAI", "TORONTO",
    "MEXICO CITY", "ISTANBUL", "RIO DE JANEIRO", "CAPE TOWN", "SEOUL",
    
    # Car companies
    "TOYOTA", "HONDA", "BMW", "FERRARI", "FORD",
    "CHEVROLET", "VOLKSWAGEN", "AUDI", "NISSAN", "HYUNDAI",
    "KIA", "MAZDA", "LEXUS", "SUBARU", "TESLA",
    
    # Colors
    "RED", "BLUE", "GREEN", "YELLOW", "BLACK",
    "WHITE", "PURPLE", "ORANGE", "PINK", "BROWN"
]
